date_from_id = 'history-from'
date_to_id = 'history-to'
price_list_id = 'table-list'
table_name = 'dlr_rl'
btn_next = 'DataTables_Table_0_next'
btns_id = 'DataTables_Table_0_paginate'
create_command = ''
